name: Build and Run Docker Container
on:
  push:
    branches:
      - WIN_dockerize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build -t pipelines .
    - name: Docker run
      working-directory: ./example_pipeline
      run: docker run pipelines poetry run pipeline run
    - name: check norm csv file
      working-directory: ./output
      run: head -n5 norm.csv
