name: Build and Run Docker Container
on:
  push:
    branches:
      - WIN_dockerize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build -t pipelines .
    - name: ls
      run: ls -a
    - name: Docker run
      run: docker run pipelines
    - name: jwalton dump docker logs
      uses: jwalton/gh-docker-logs@v2
    - name: pipeline logs
      run: docker compose logs -f -t pipelines