name: Build and Run Docker Container
on:
  push:
    branches:
      - WIN_dockerize
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build -t pipelines .
    - name: Docker run
      run: docker run pipelines --mount=.
