name: Build and Run Docker Container
on:
  push:
    branches:
      - WIN_dockerize
      - test_branch
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up
      run: docker compose up -d
    - name: Docker logs
      run: docker compose logs -f -t
    - name: Show norm file
      working-directory: example_pipeline/output
      run: head -n5 norm.csv