name: Build and Run Docker Container
on:
  push:
    branches: 
      - WIN_dockerize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up
      run: docker compose up -d --build --no-TTY
    - name: Dump docker logs
      uses: jwalton/gh-docker-logs@v2
    - name: ls command in current directory
      run: ls -a