name: Build and Run Docker Container
on:
  push:
    branches:
      - WIN_dockerize
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: [build] Docker build
      run: docker build -t pipelines .
    - name: [run] Docker run
      run: docker run pipelines
    - name: [check] Check norm.csv file
      working-directory: ./output
      run: head -n5 norm.csv
